runtime: java23  # Specify your runtime (e.g., java11, java17)
instance_class: F2  # Choose an instance class based on your requirements
entrypoint: java -jar target/rest-demo1-0.0.1-SNAPSHOT.jar  # Adjust based on your JAR file name

handlers:
- url: /.*
  script: this field is required, but ignored