
spring:
   datasource: 
       url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
       username: root
       password: admin
       
#jpa settings
jpa:hibernate.ddl_auto: create

#google cloud instnace
# spring:
#     datasource: 
#         url: jdbc:mysql://>GOOGLE_CLOUD_ADDRESS>/vendor_cloud?useSSL=false
#         username: mish <GOOGLE_CLOUD_USERNAME>
#         password: mish <GOOGLE_CLOUD_USER_PASSWORD>
        
# #jpa settings
# jpa:hibernate.ddl_auto: create
